import React, {createContext, useContext, useEffect, useMemo, useState} from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type AppLanguage = 'English' | 'Hindi' | 'Marathi';
export type ChartStyle = 'North' | 'South';

interface AppSettingsState {
  language: AppLanguage;
  chartStyle: ChartStyle;
  ayanamsa: string;
  notifications: boolean;
  darkMode: boolean;
}

interface AppSettingsContextValue extends AppSettingsState {
  isReady: boolean;
  setLanguage: (lang: AppLanguage) => void;
  setChartStyle: (style: ChartStyle) => void;
  setAyanamsa: (value: string) => void;
  setNotifications: (value: boolean) => void;
  setDarkMode: (value: boolean) => void;
  saveSettings: () => Promise<void>;
  t: (key: string) => string;
}

const STORAGE_KEY = 'kundali_app_settings';

const DEFAULT_SETTINGS: AppSettingsState = {
  language: 'English',
  chartStyle: 'North',
  ayanamsa: 'Lahiri',
  notifications: true,
  darkMode: false,
};

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  English: {
    settings: 'Settings',
    language: 'Language',
    save_preferences: 'Save Preferences',
    saved: 'Preferences saved successfully',
    navigation: 'Navigation',
    home: 'Home',
    profiles: 'User Profiles',
    horoscope: 'Horoscope',
    ask_question: 'Ask Question',
    remedies: 'Remedies',
    career_guidance: 'Career Guidance',
    financial_outlook: 'Financial Outlook',
    gemstone_guide: 'Gemstone Guide',
    numerology: 'Numerology',
    matchmaking: 'Matchmaking',
    soulmate_analysis: 'Soulmate Analysis',
    muhurat_finder: 'Muhurat Finder',
    varshaphal: 'Varshaphal',
    dasha_analysis: 'Dasha Analysis',
    name_recommendation: 'Name Recommendation',
    stotras_prayers: 'Stotras & Prayers',
    vedic_astrology_ai: 'Vedic Astrology AI',
    guest_mode_limited: 'Guest Mode - Limited Features',
    welcome_user: 'Welcome',
    no_birth_profile_found: 'No birth profile found',
    create_profile_unlock_features: 'Tap here to create your profile and unlock all features',
    astrology_services: 'Astrology Services',
    logout: 'Logout',
    confirm_logout: 'Are you sure you want to logout?',
    cancel: 'Cancel',
    profile_required: 'Profile Required',
    create_profile_first: 'To use astrology services, please create your birth profile first.',
    add_birth_details: 'Add your name, date of birth, time and place so we can calculate your personalised chart.',
    create_profile: 'Create Profile',
    maybe_later: 'Maybe Later',
    current_dasha: 'Current Dasha',
    mahadasha: 'Mahadasha',
    antardasha: 'Antardasha',
    action_view: 'View',
    action_ask: 'Ask',
    action_analyze: 'Analyze',
    action_check: 'Check',
    action_find: 'Find',
    action_open: 'Open',
    action_suggest: 'Suggest',
    feature_ask_question_desc: 'Instant answers about career, wealth, relationships',
    feature_career_desc: 'Best career & profession from your chart',
    feature_financial_desc: 'Wealth timing & financial planetary transits',
    feature_gemstone_desc: 'Personalized recommendations from chart analysis',
    feature_numerology_desc: 'Life Path, Expression & Soul numbers',
    feature_matchmaking_desc: 'Kundali Milan & compatibility analysis',
    feature_muhurat_desc: 'Auspicious timing for important events',
    feature_varshaphal_desc: 'Annual predictions & yearly forecast',
    feature_dasha_desc: 'Detailed planetary period predictions',
    feature_stotras_desc: 'Sacred Vedic hymns for peace, protection and remedies',
    feature_remedies_desc: 'Lal Kitab remedies & lifestyle changes',
    feature_name_guide_desc: 'Lucky names based on nakshatra',
    feature_soulmate_desc: 'Soulmate traits & relationship insights',
    detailed_dasha_analysis: 'Detailed Dasha Analysis',
    profile_label: 'Profile',
    dob_placeholder: 'Date of birth (YYYY-MM-DD)',
    loading: 'Loading...',
    get_current_dasha: 'Get Current Dasha',
    start: 'Start',
    end: 'End',
    duration: 'Duration',
    years: 'years',
    what_happening_now: 'What Is Happening Now',
    what_should_do: 'What You Should Do',
    what_to_avoid: 'What To Avoid',
    remedies_period: 'Remedies For This Period',
    antardasha_support: 'Antardasha support',
    dasha_tip: 'Tip: For personalized remedies and gemstone recommendations, open the dedicated sections below.',
    go_to_remedies: 'Go To Remedies',
    go_to_gemstone: 'Go To Gemstone',
    go_to_stotras: 'Go To Stotras & Prayers',
    dasha_error: 'Dasha Error',
    failed_fetch_dasha: 'Failed to fetch dasha',
    numerology_error: 'Numerology Error',
    failed_calculate_numerology: 'Failed to calculate numerology',
    numerology_title: 'Numerology',
    full_name: 'Full name',
    calculating: 'Calculating...',
    calculate_numerology: 'Calculate Numerology',
    life_path: 'Life Path',
    destiny: 'Destiny',
    soul: 'Soul',
    personality: 'Personality',
    numerology_insights: 'Your Numerology Insights',
    archetype: 'Archetype',
    life_path_strengths: 'Life Path Strengths',
    destiny_talent: 'Destiny Talent',
    core_traits: 'Core Traits',
    growth_areas: 'Growth Areas',
    useful_numbers: 'Useful Numbers',
    birthday_number: 'Birthday Number',
    personal_year: 'Personal Year',
    maturity_number: 'Maturity Number',
    master_numbers: 'Master Numbers',
    karmic_lessons: 'Karmic Lessons',
    varshaphal_title: 'Varshaphal - Annual Predictions',
    varshaphal_subtitle: 'Comprehensive yearly forecast based on your chart',
    generate_annual_predictions: 'Generate Annual Predictions',
    varshaphal_alert_title: 'Varshaphal',
    varshaphal_alert_message: 'Unable to analyze. Please ensure an active profile exists.',
    profile_default: 'Profile',
    muntha_position: 'Muntha Position',
    house: 'House',
    muntha_note_prefix: 'The Muntha for your',
    muntha_note_suffix: 'Varshaphal is in the',
    muntha_note_suffix_2: 'th house, which is a key area of focus this year.',
    overall_year_outlook: 'Overall Year Outlook',
    overall_rating: 'Overall Rating',
    best_months: 'Best Months',
    key_planet: 'Key Planet',
    detailed_annual_forecast: 'Detailed Annual Forecast',
    area: 'Area',
    score: 'Score',
    challenges: 'Challenges',
    reanalyze: 'Re-analyze',
    menu_tip_title: 'Explore More Features',
    menu_tip_body: 'Use the ☰ button at the top-left to open the full menu with all astrology tools.',
    menu_tip_dismiss: 'Got it',
  },
  Hindi: {
    settings: 'सेटिंग्स',
    language: 'भाषा',
    save_preferences: 'प्राथमिकताएं सहेजें',
    saved: 'प्राथमिकताएं सफलतापूर्वक सहेजी गईं',
    navigation: 'नेविगेशन',
    home: 'होम',
    profiles: 'यूज़र प्रोफाइल',
    horoscope: 'राशिफल',
    ask_question: 'प्रश्न पूछें',
    remedies: 'उपाय',
    career_guidance: 'कैरियर मार्गदर्शन',
    financial_outlook: 'वित्तीय दृष्टिकोण',
    gemstone_guide: 'रत्न मार्गदर्शिका',
    numerology: 'अंक ज्योतिष',
    matchmaking: 'मैचमेकिंग',
    soulmate_analysis: 'सोलमेट विश्लेषण',
    muhurat_finder: 'मुहूर्त खोज',
    varshaphal: 'वर्षफल',
    dasha_analysis: 'दशा विश्लेषण',
    name_recommendation: 'नाम सुझाव',
    stotras_prayers: 'स्तोत्र और प्रार्थना',
    vedic_astrology_ai: 'वैदिक ज्योतिष AI',
    guest_mode_limited: 'गेस्ट मोड - सीमित सुविधाएं',
    welcome_user: 'स्वागत है',
    no_birth_profile_found: 'जन्म प्रोफाइल नहीं मिला',
    create_profile_unlock_features: 'अपनी प्रोफाइल बनाने और सभी सुविधाएं अनलॉक करने के लिए यहां टैप करें',
    astrology_services: 'ज्योतिष सेवाएं',
    logout: 'लॉगआउट',
    confirm_logout: 'क्या आप लॉगआउट करना चाहते हैं?',
    cancel: 'रद्द करें',
    profile_required: 'प्रोफाइल आवश्यक',
    create_profile_first: 'ज्योतिष सेवाओं का उपयोग करने के लिए पहले अपनी जन्म प्रोफाइल बनाएं।',
    add_birth_details: 'अपना नाम, जन्म तिथि, समय और स्थान जोड़ें ताकि हम आपकी व्यक्तिगत कुंडली बना सकें।',
    create_profile: 'प्रोफाइल बनाएं',
    maybe_later: 'बाद में',
    current_dasha: 'वर्तमान दशा',
    mahadasha: 'महादशा',
    antardasha: 'अंतरदशा',
    action_view: 'देखें',
    action_ask: 'पूछें',
    action_analyze: 'विश्लेषण',
    action_check: 'जांचें',
    action_find: 'खोजें',
    action_open: 'खोलें',
    action_suggest: 'सुझाव',
    feature_ask_question_desc: 'करियर, धन और संबंधों पर तुरंत उत्तर',
    feature_career_desc: 'आपकी कुंडली से सर्वोत्तम करियर और पेशा',
    feature_financial_desc: 'धन का समय और वित्तीय ग्रह गोचर',
    feature_gemstone_desc: 'कुंडली विश्लेषण से व्यक्तिगत सुझाव',
    feature_numerology_desc: 'लाइफ पाथ, एक्सप्रेशन और सोल नंबर',
    feature_matchmaking_desc: 'कुंडली मिलान और संगतता विश्लेषण',
    feature_muhurat_desc: 'महत्वपूर्ण कार्यों के लिए शुभ समय',
    feature_varshaphal_desc: 'वार्षिक भविष्यवाणी और सालाना पूर्वानुमान',
    feature_dasha_desc: 'विस्तृत ग्रह अवधि भविष्यवाणी',
    feature_stotras_desc: 'शांति, सुरक्षा और उपायों के लिए वैदिक स्तोत्र',
    feature_remedies_desc: 'लाल किताब उपाय और जीवनशैली बदलाव',
    feature_name_guide_desc: 'नक्षत्र के आधार पर शुभ नाम',
    feature_soulmate_desc: 'सोलमेट गुण और संबंध अंतर्दृष्टि',
    detailed_dasha_analysis: 'विस्तृत दशा विश्लेषण',
    profile_label: 'प्रोफाइल',
    dob_placeholder: 'जन्म तिथि (YYYY-MM-DD)',
    loading: 'लोड हो रहा है...',
    get_current_dasha: 'वर्तमान दशा देखें',
    start: 'आरंभ',
    end: 'समाप्ति',
    duration: 'अवधि',
    years: 'वर्ष',
    what_happening_now: 'अभी क्या हो रहा है',
    what_should_do: 'क्या करना चाहिए',
    what_to_avoid: 'किससे बचें',
    remedies_period: 'इस अवधि के उपाय',
    antardasha_support: 'अंतरदशा सहयोग',
    dasha_tip: 'टिप: व्यक्तिगत उपाय और रत्न सुझावों के लिए नीचे दिए गए अनुभाग खोलें।',
    go_to_remedies: 'उपाय पर जाएं',
    go_to_gemstone: 'रत्न पर जाएं',
    go_to_stotras: 'स्तोत्र और प्रार्थना पर जाएं',
    dasha_error: 'दशा त्रुटि',
    failed_fetch_dasha: 'दशा प्राप्त करने में विफल',
    numerology_error: 'अंक ज्योतिष त्रुटि',
    failed_calculate_numerology: 'अंक ज्योतिष गणना विफल',
    numerology_title: 'अंक ज्योतिष',
    full_name: 'पूरा नाम',
    calculating: 'गणना हो रही है...',
    calculate_numerology: 'अंक ज्योतिष निकालें',
    life_path: 'लाइफ पाथ',
    destiny: 'भाग्य',
    soul: 'आत्मा',
    personality: 'व्यक्तित्व',
    numerology_insights: 'आपकी अंक ज्योतिष अंतर्दृष्टि',
    archetype: 'आर्केटाइप',
    life_path_strengths: 'लाइफ पाथ शक्तियां',
    destiny_talent: 'भाग्य प्रतिभा',
    core_traits: 'मुख्य गुण',
    growth_areas: 'विकास के क्षेत्र',
    useful_numbers: 'उपयोगी अंक',
    birthday_number: 'जन्मदिन अंक',
    personal_year: 'व्यक्तिगत वर्ष',
    maturity_number: 'परिपक्वता अंक',
    master_numbers: 'मास्टर नंबर',
    karmic_lessons: 'कर्मिक पाठ',
    varshaphal_title: 'वर्षफल - वार्षिक भविष्यवाणी',
    varshaphal_subtitle: 'आपकी कुंडली पर आधारित विस्तृत सालाना पूर्वानुमान',
    generate_annual_predictions: 'वार्षिक भविष्यवाणी बनाएं',
    varshaphal_alert_title: 'वर्षफल',
    varshaphal_alert_message: 'विश्लेषण संभव नहीं है। कृपया सक्रिय प्रोफाइल सुनिश्चित करें।',
    profile_default: 'प्रोफाइल',
    muntha_position: 'मुन्था स्थिति',
    house: 'भाव',
    muntha_note_prefix: 'आपके',
    muntha_note_suffix: 'वर्षफल में मुन्था',
    muntha_note_suffix_2: 'भाव में है, जो इस वर्ष का मुख्य फोकस क्षेत्र है।',
    overall_year_outlook: 'संपूर्ण वर्ष का दृष्टिकोण',
    overall_rating: 'समग्र रेटिंग',
    best_months: 'श्रेष्ठ महीने',
    key_planet: 'मुख्य ग्रह',
    detailed_annual_forecast: 'विस्तृत वार्षिक पूर्वानुमान',
    area: 'क्षेत्र',
    score: 'स्कोर',
    challenges: 'चुनौतियां',
    reanalyze: 'फिर से विश्लेषण',
    menu_tip_title: 'और सुविधाएं देखें',
    menu_tip_body: 'सभी ज्योतिष टूल्स वाला पूरा मेनू खोलने के लिए ऊपर बाईं ओर ☰ बटन का उपयोग करें।',
    menu_tip_dismiss: 'ठीक है',
  },
  Marathi: {
    settings: 'सेटिंग्स',
    language: 'भाषा',
    save_preferences: 'प्राधान्ये जतन करा',
    saved: 'प्राधान्ये यशस्वीरीत्या जतन झाली',
    navigation: 'नेव्हिगेशन',
    home: 'मुख्यपृष्ठ',
    profiles: 'वापरकर्ता प्रोफाइल',
    horoscope: 'कुंडली',
    ask_question: 'प्रश्न विचारा',
    remedies: 'उपाय',
    career_guidance: 'करिअर मार्गदर्शन',
    financial_outlook: 'आर्थिक दृष्टीकोन',
    gemstone_guide: 'रत्न मार्गदर्शक',
    numerology: 'अंकशास्त्र',
    matchmaking: 'जुळवणी',
    soulmate_analysis: 'सोलमेट विश्लेषण',
    muhurat_finder: 'मुहूर्त शोध',
    varshaphal: 'वर्षफल',
    dasha_analysis: 'दशा विश्लेषण',
    name_recommendation: 'नाव शिफारस',
    stotras_prayers: 'स्तोत्र आणि प्रार्थना',
    vedic_astrology_ai: 'वैदिक ज्योतिष AI',
    guest_mode_limited: 'गेस्ट मोड - मर्यादित सुविधा',
    welcome_user: 'स्वागत',
    no_birth_profile_found: 'जन्म प्रोफाइल सापडले नाही',
    create_profile_unlock_features: 'आपले प्रोफाइल तयार करून सर्व सुविधा अनलॉक करण्यासाठी येथे टॅप करा',
    astrology_services: 'ज्योतिष सेवा',
    logout: 'लॉगआउट',
    confirm_logout: 'तुम्ही लॉगआउट करू इच्छिता का?',
    cancel: 'रद्द करा',
    profile_required: 'प्रोफाइल आवश्यक',
    create_profile_first: 'ज्योतिष सेवा वापरण्यासाठी कृपया आधी जन्म प्रोफाइल तयार करा.',
    add_birth_details: 'आपले नाव, जन्मतारीख, वेळ आणि ठिकाण जोडा, म्हणजे आम्ही तुमची वैयक्तिक कुंडली तयार करू शकतो.',
    create_profile: 'प्रोफाइल तयार करा',
    maybe_later: 'नंतर',
    current_dasha: 'सध्याची दशा',
    mahadasha: 'महादशा',
    antardasha: 'अंतरदशा',
    action_view: 'पहा',
    action_ask: 'विचारा',
    action_analyze: 'विश्लेषण',
    action_check: 'तपासा',
    action_find: 'शोधा',
    action_open: 'उघडा',
    action_suggest: 'सुचवा',
    feature_ask_question_desc: 'करिअर, संपत्ती, नातेसंबंधांवरील तत्काळ उत्तरे',
    feature_career_desc: 'तुमच्या कुंडलीवर आधारित सर्वोत्तम करिअर',
    feature_financial_desc: 'संपत्तीची वेळ आणि आर्थिक ग्रह गोचर',
    feature_gemstone_desc: 'कुंडली विश्लेषणावर आधारित वैयक्तिक शिफारसी',
    feature_numerology_desc: 'लाइफ पाथ, एक्सप्रेशन आणि सोल नंबर',
    feature_matchmaking_desc: 'कुंडली मिलन आणि सुसंगतता विश्लेषण',
    feature_muhurat_desc: 'महत्त्वाच्या कामांसाठी शुभ वेळ',
    feature_varshaphal_desc: 'वार्षिक भाकीत आणि वर्षभराचा अंदाज',
    feature_dasha_desc: 'तपशीलवार ग्रहकाल भाकीत',
    feature_stotras_desc: 'शांती, संरक्षण आणि उपायांसाठी वैदिक स्तोत्रे',
    feature_remedies_desc: 'लाल किताब उपाय आणि जीवनशैली बदल',
    feature_name_guide_desc: 'नक्षत्रावर आधारित शुभ नावे',
    feature_soulmate_desc: 'सोलमेट गुणधर्म आणि नातेसंबंध अंतर्दृष्टी',
    detailed_dasha_analysis: 'तपशीलवार दशा विश्लेषण',
    profile_label: 'प्रोफाइल',
    dob_placeholder: 'जन्मतारीख (YYYY-MM-DD)',
    loading: 'लोड होत आहे...',
    get_current_dasha: 'सध्याची दशा पहा',
    start: 'सुरुवात',
    end: 'समाप्ती',
    duration: 'कालावधी',
    years: 'वर्षे',
    what_happening_now: 'आता काय घडत आहे',
    what_should_do: 'काय करावे',
    what_to_avoid: 'काय टाळावे',
    remedies_period: 'या काळातील उपाय',
    antardasha_support: 'अंतरदशा सहाय्य',
    dasha_tip: 'टीप: वैयक्तिक उपाय आणि रत्न शिफारसींसाठी खालील विभाग उघडा.',
    go_to_remedies: 'उपायांकडे जा',
    go_to_gemstone: 'रत्नांकडे जा',
    go_to_stotras: 'स्तोत्र आणि प्रार्थनेकडे जा',
    dasha_error: 'दशा त्रुटी',
    failed_fetch_dasha: 'दशा मिळवता आली नाही',
    numerology_error: 'अंकशास्त्र त्रुटी',
    failed_calculate_numerology: 'अंकशास्त्र गणना अयशस्वी',
    numerology_title: 'अंकशास्त्र',
    full_name: 'पूर्ण नाव',
    calculating: 'गणना सुरू आहे...',
    calculate_numerology: 'अंकशास्त्र मोजा',
    life_path: 'लाइफ पाथ',
    destiny: 'भाग्य',
    soul: 'आत्मा',
    personality: 'व्यक्तिमत्व',
    numerology_insights: 'तुमचे अंकशास्त्रीय निष्कर्ष',
    archetype: 'आर्केटाइप',
    life_path_strengths: 'लाइफ पाथ शक्ती',
    destiny_talent: 'भाग्य प्रतिभा',
    core_traits: 'मुख्य गुण',
    growth_areas: 'विकास क्षेत्रे',
    useful_numbers: 'उपयुक्त संख्या',
    birthday_number: 'वाढदिवस संख्या',
    personal_year: 'वैयक्तिक वर्ष',
    maturity_number: 'परिपक्वता संख्या',
    master_numbers: 'मास्टर संख्या',
    karmic_lessons: 'कर्म धडे',
    varshaphal_title: 'वर्षफल - वार्षिक भाकीत',
    varshaphal_subtitle: 'तुमच्या कुंडलीवर आधारित सविस्तर वार्षिक अंदाज',
    generate_annual_predictions: 'वार्षिक भाकीत तयार करा',
    varshaphal_alert_title: 'वर्षफल',
    varshaphal_alert_message: 'विश्लेषण करता आले नाही. कृपया सक्रिय प्रोफाइल असल्याची खात्री करा.',
    profile_default: 'प्रोफाइल',
    muntha_position: 'मुन्था स्थान',
    house: 'भाव',
    muntha_note_prefix: 'तुमच्या',
    muntha_note_suffix: 'वर्षफलमध्ये मुन्था',
    muntha_note_suffix_2: 'भावात आहे, जो या वर्षातील महत्त्वाचा फोकस आहे.',
    overall_year_outlook: 'एकूण वर्षाचा आढावा',
    overall_rating: 'एकूण रेटिंग',
    best_months: 'सर्वोत्तम महिने',
    key_planet: 'मुख्य ग्रह',
    detailed_annual_forecast: 'तपशीलवार वार्षिक अंदाज',
    area: 'क्षेत्र',
    score: 'गुण',
    challenges: 'आव्हाने',
    reanalyze: 'पुन्हा विश्लेषण',
    menu_tip_title: 'अधिक सुविधा शोधा',
    menu_tip_body: 'सर्व ज्योतिष साधने असलेला पूर्ण मेनू उघडण्यासाठी वर डाव्या बाजूचा ☰ बटण वापरा.',
    menu_tip_dismiss: 'समजले',
  },
};

const AppSettingsContext = createContext<AppSettingsContextValue | undefined>(undefined);

export const AppSettingsProvider = ({children}: {children: React.ReactNode}) => {
  const [settings, setSettings] = useState<AppSettingsState>(DEFAULT_SETTINGS);
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    const load = async () => {
      try {
        const raw = await AsyncStorage.getItem(STORAGE_KEY);
        if (raw) {
          const parsed = JSON.parse(raw);
          setSettings({...DEFAULT_SETTINGS, ...parsed});
        }
      } catch {
        setSettings(DEFAULT_SETTINGS);
      } finally {
        setIsReady(true);
      }
    };
    load();
  }, []);

  useEffect(() => {
    if (!isReady) return;
    AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(settings)).catch(() => {
      // Ignore storage errors; explicit save remains available.
    });
  }, [settings, isReady]);

  const saveSettings = async () => {
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(settings));
  };

  const value = useMemo<AppSettingsContextValue>(
    () => ({
      ...settings,
      isReady,
      setLanguage: language => setSettings(prev => ({...prev, language})),
      setChartStyle: chartStyle => setSettings(prev => ({...prev, chartStyle})),
      setAyanamsa: ayanamsa => setSettings(prev => ({...prev, ayanamsa})),
      setNotifications: notifications => setSettings(prev => ({...prev, notifications})),
      setDarkMode: darkMode => setSettings(prev => ({...prev, darkMode})),
      saveSettings,
      t: key => TRANSLATIONS[settings.language]?.[key] || TRANSLATIONS.English[key] || key,
    }),
    [settings, isReady],
  );

  return <AppSettingsContext.Provider value={value}>{children}</AppSettingsContext.Provider>;
};

export const useAppSettings = () => {
  const ctx = useContext(AppSettingsContext);
  if (!ctx) {
    throw new Error('useAppSettings must be used inside AppSettingsProvider');
  }
  return ctx;
};
